name: 🧪 test

on:
    push:
        branches:
            - "main"
        paths:
            - '**.go'
            - '**.mod'
    pull_request:
        branches:
          - "main"
        paths:
            - '**.go'
            - '**.mod'
    workflow_dispatch:

jobs:
    build:
        name: Test
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-12]
        runs-on: ${{ matrix.os }}
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version:  '>=1.20'
            -
                name: Checkout the code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            - 
                name: Go modules hygine
                run: |
                    go clean -modcache
                    go mod tidy
                working-directory: .
            -
                name: Go test
                run: go test -v ./...
                working-directory: .